### ISSUE TITLE
question about 32 channel frida app go 4

### ISSUE THREAD

**Issue by Maxym77** [o-gs/DJI_FC_Patcher#11]
hi mati ,
now with galilelo i need to enable 32 CH on frida 4.3 or i leave default? my maximum grabbed satellites is 27 i have seen .. thanks

**Comment by Matioupi** [comment]
No need to enable anything on frida app side. All configuration is done on bird side. The app mod is needed to be executed only once, so it's ok if you do it on Android once the first time and then turns to another app.

As for the 27 sats, this also the highest count I've been able to get (maybe I had an ultra short "28" one day). This is due to the configuration of constellations in the sky.

At my place today, the satellites forecast for today, GPS+GLO+GAL at 5° horizon is :

![image](https://user-images.githubusercontent.com/5566194/44955700-f0fa8c00-aeb7-11e8-89c6-2229e8c3ab0b.png)

so there are only short times when you get more than 27 sats, and you never reach the receiver max capability of 32 channels.

Beginning of 2019 thereshould be 5 more active Galileos (maybe even a little more if we are lucky) so the figure could rise a little bit.
